# =============================================================================
# Strømkalkulator Utility Meter Package
# =============================================================================
#
# Denne pakken setter opp utility_meter med dag/natt-tariffer for
# nøyaktig forbrukssporing som matcher nettleie-fakturaen.
#
# HVORFOR BRUKE DENNE?
# - Splitte forbruk på dag/natt-tariff (for faktura-validering)
# - Beregne månedlige kostnader per komponent
# - Se om du sparer vs. Norgespris
#
# OPPSETT:
# 1. Kopier denne filen til /config/packages/
# 2. Aktiver packages i configuration.yaml:
#    homeassistant:
#      packages: !include_dir_named packages
# 3. VIKTIG: Endre sensor-navnene nedenfor til dine faktiske sensorer
# 4. Start Home Assistant på nytt
#
# TILPASS DISSE VERDIENE (søk og erstatt):
#   sensor.BYTT_EFFEKT_SENSOR  → Din effekt-sensor (W), f.eks. sensor.tibber_pulse_power
#
# =============================================================================

# -----------------------------------------------------------------------------
# RIEMANN SUM - Konverter effekt (W) til energi (kWh)
# -----------------------------------------------------------------------------
# Hvis du allerede har en kWh-sensor (f.eks. fra Tibber eller AMS-leser),
# kan du kommentere ut denne seksjonen og bruke den direkte.

sensor:
  - platform: integration
    source: sensor.BYTT_EFFEKT_SENSOR    # <-- BYTT UT med din effekt-sensor (W)
    name: "Strøm energiforbruk"
    unique_id: stromkalkulator_energiforbruk
    unit_prefix: k
    round: 3
    method: left

# -----------------------------------------------------------------------------
# UTILITY METER - Forbrukssporing med dag/natt-tariffer
# -----------------------------------------------------------------------------

utility_meter:
  # Daglig forbruk per tariff
  strom_daglig:
    source: sensor.strom_energiforbruk   # <-- Eller din kWh-sensor direkte
    name: "Strøm daglig"
    unique_id: stromkalkulator_daglig
    cycle: daily
    tariffs:
      - dag
      - natt

  # Månedlig forbruk per tariff
  strom_maanedlig:
    source: sensor.strom_energiforbruk   # <-- Eller din kWh-sensor direkte
    name: "Strøm månedlig"
    unique_id: stromkalkulator_maanedlig
    cycle: monthly
    tariffs:
      - dag
      - natt

  # Årlig forbruk per tariff (valgfritt)
  strom_aarlig:
    source: sensor.strom_energiforbruk
    name: "Strøm årlig"
    unique_id: stromkalkulator_aarlig
    cycle: yearly
    tariffs:
      - dag
      - natt

# -----------------------------------------------------------------------------
# TEMPLATE SENSORER - Månedlig kostnadsberegning
# -----------------------------------------------------------------------------

template:
  - sensor:
      # Månedlig nettleie-kostnad (energiledd + kapasitetsledd)
      - name: "Månedlig nettleie kostnad"
        unique_id: stromkalkulator_maanedlig_nettleie_kostnad
        unit_of_measurement: "kr"
        device_class: monetary
        icon: mdi:transmission-tower
        state: >
          {% set dag_kwh = states('sensor.strom_maanedlig_dag') | float(0) %}
          {% set natt_kwh = states('sensor.strom_maanedlig_natt') | float(0) %}
          {% set dag_pris = states('sensor.energiledd_dag') | float(0) %}
          {% set natt_pris = states('sensor.energiledd_natt_helg') | float(0) %}
          {% set kapasitet = states('sensor.kapasitetstrinn') | float(0) %}
          {{ ((dag_kwh * dag_pris) + (natt_kwh * natt_pris) + kapasitet) | round(2) }}
        attributes:
          dag_forbruk_kwh: "{{ states('sensor.strom_maanedlig_dag') | float(0) | round(1) }}"
          natt_forbruk_kwh: "{{ states('sensor.strom_maanedlig_natt') | float(0) | round(1) }}"
          dag_kostnad_kr: "{{ (states('sensor.strom_maanedlig_dag') | float(0) * states('sensor.energiledd_dag') | float(0)) | round(2) }}"
          natt_kostnad_kr: "{{ (states('sensor.strom_maanedlig_natt') | float(0) * states('sensor.energiledd_natt_helg') | float(0)) | round(2) }}"
          kapasitetsledd_kr: "{{ states('sensor.kapasitetstrinn') | float(0) | round(0) }}"

      # Månedlig forbruksavgift
      - name: "Månedlig forbruksavgift"
        unique_id: stromkalkulator_maanedlig_forbruksavgift
        unit_of_measurement: "kr"
        device_class: monetary
        icon: mdi:bank
        state: >
          {% set total_kwh = states('sensor.strom_maanedlig_dag') | float(0) + states('sensor.strom_maanedlig_natt') | float(0) %}
          {% set avgift = states('sensor.forbruksavgift') | float(0) %}
          {{ (total_kwh * avgift) | round(2) }}

      # Månedlig Enova-avgift
      - name: "Månedlig Enovaavgift"
        unique_id: stromkalkulator_maanedlig_enovaavgift
        unit_of_measurement: "kr"
        device_class: monetary
        icon: mdi:leaf
        state: >
          {% set total_kwh = states('sensor.strom_maanedlig_dag') | float(0) + states('sensor.strom_maanedlig_natt') | float(0) %}
          {% set avgift = states('sensor.enovaavgift') | float(0) %}
          {{ (total_kwh * avgift) | round(2) }}

      # Månedlig strømstøtte (mottatt)
      - name: "Månedlig strømstøtte"
        unique_id: stromkalkulator_maanedlig_stromstotte
        unit_of_measurement: "kr"
        device_class: monetary
        icon: mdi:cash-plus
        state: >
          {% set total_kwh = states('sensor.strom_maanedlig_dag') | float(0) + states('sensor.strom_maanedlig_natt') | float(0) %}
          {% set stotte = states('sensor.stromstotte') | float(0) %}
          {{ (total_kwh * stotte) | round(2) }}
        attributes:
          forklaring: "Estimert strømstøtte basert på gjennomsnittlig støtte-sats"

      # Månedlig energiledd dag (kr)
      - name: "Månedlig energiledd dag"
        unique_id: stromkalkulator_maanedlig_energiledd_dag
        unit_of_measurement: "kr"
        device_class: monetary
        icon: mdi:weather-sunny
        state: >
          {% set kwh = states('sensor.strom_maanedlig_dag') | float(0) %}
          {% set pris = states('sensor.energiledd_dag') | float(0) %}
          {{ (kwh * pris) | round(2) }}

      # Månedlig energiledd natt (kr)
      - name: "Månedlig energiledd natt"
        unique_id: stromkalkulator_maanedlig_energiledd_natt
        unit_of_measurement: "kr"
        device_class: monetary
        icon: mdi:weather-night
        state: >
          {% set kwh = states('sensor.strom_maanedlig_natt') | float(0) %}
          {% set pris = states('sensor.energiledd_natt_helg') | float(0) %}
          {{ (kwh * pris) | round(2) }}

      # Besparelse vs Norgespris denne måneden
      - name: "Besparelse vs Norgespris"
        unique_id: stromkalkulator_besparelse_norgespris
        unit_of_measurement: "kr"
        device_class: monetary
        icon: mdi:piggy-bank
        state: >
          {% set total_kwh = states('sensor.strom_maanedlig_dag') | float(0) + states('sensor.strom_maanedlig_natt') | float(0) %}
          {% set diff_per_kwh = states('sensor.prisforskjell_norgespris') | float(0) %}
          {{ (total_kwh * diff_per_kwh * -1) | round(2) }}
        attributes:
          forklaring: "Positiv = du sparer, Negativ = du taper vs Norgespris (50 øre/kWh)"

      # Total nettleie å betale (etter strømstøtte)
      - name: "Månedlig nettleie etter støtte"
        unique_id: stromkalkulator_maanedlig_nettleie_etter_stotte
        unit_of_measurement: "kr"
        device_class: monetary
        icon: mdi:receipt-text
        state: >
          {% set nettleie = states('sensor.maanedlig_nettleie_kostnad') | float(0) %}
          {% set avgifter = states('sensor.maanedlig_forbruksavgift') | float(0) + states('sensor.maanedlig_enovaavgift') | float(0) %}
          {% set stotte = states('sensor.maanedlig_stromstotte') | float(0) %}
          {{ (nettleie + avgifter - stotte) | round(2) }}
        attributes:
          nettleie_kr: "{{ states('sensor.maanedlig_nettleie_kostnad') | float(0) | round(2) }}"
          forbruksavgift_kr: "{{ states('sensor.maanedlig_forbruksavgift') | float(0) | round(2) }}"
          enovaavgift_kr: "{{ states('sensor.maanedlig_enovaavgift') | float(0) | round(2) }}"
          stromstotte_kr: "{{ states('sensor.maanedlig_stromstotte') | float(0) | round(2) }}"

# -----------------------------------------------------------------------------
# AUTOMATISERING - Tariff-bytte
# -----------------------------------------------------------------------------

automation:
  # Bytt tariff når Strømkalkulator melder dag/natt-endring
  - id: stromkalkulator_tariff_bytte
    alias: "Strømkalkulator: Oppdater tariff"
    description: "Bytter utility_meter tariff basert på sensor.tariff"
    trigger:
      - platform: state
        entity_id: sensor.tariff
        to:
          - dag
          - natt
    action:
      - service: select.select_option
        target:
          entity_id:
            - select.strom_daglig
            - select.strom_maanedlig
            - select.strom_aarlig
        data:
          option: "{{ trigger.to_state.state }}"
    mode: single

  # Sett riktig tariff ved oppstart
  - id: stromkalkulator_tariff_oppstart
    alias: "Strømkalkulator: Sett tariff ved oppstart"
    description: "Setter riktig tariff når Home Assistant starter"
    trigger:
      - platform: homeassistant
        event: start
    condition:
      - condition: state
        entity_id: sensor.tariff
        state:
          - dag
          - natt
    action:
      - delay: "00:00:30"
      - service: select.select_option
        target:
          entity_id:
            - select.strom_daglig
            - select.strom_maanedlig
            - select.strom_aarlig
        data:
          option: "{{ states('sensor.tariff') }}"
    mode: single
